### ISSUE TITLE
AEM installer fails during restart

### ISSUE THREAD

**Issue by ssachtleben** [remcorakers/aem-docker-getting-started#4]
Hi,

since around 2 weeks I get this exception during start:

```
2020-03-18 15:09:34: aem_installer.py called with params: {'runmode': 'publish,nosamplecontent,local', 'port': '4503', 'filename': 'AEM_6.x_Quickstart.jar'}
2020-03-18 15:09:34: Start installing packages
2020-03-18 15:09:34: Starting AEM with arguments: file: AEM_6.x_Quickstart.jar, port: 4503, runmode: publish,nosamplecontent,local
2020-03-18 15:09:34: Trying to start AEM (attempt 1)
Loading quickstart properties: default
Loading quickstart properties: instance
Low-memory action set to fork
Using 64bit VM settings, min.heap=1024MB, min permgen=256MB, default fork arguments=[-Xmx1024m, -XX:MaxPermSize=256m]
The JVM reports a heap size of 7851 MB, meets our expectation of 1024 MB +/- 20
No console, will fork to get enough memory
Not forking JVM as -nofork option is set
Setting properties from filename '/opt/aem/AEM_6.x_Quickstart.jar'
Setting 'sling.run.modes' to 'publish,nosamplecontent,local' from command line.
Unable to setup Swing UI, will use system console only (java.awt.HeadlessException)
Verbose option not active, closing stdin and redirecting stdout and stderr
Redirecting stdout to /opt/aem/crx-quickstart/logs/stdout.log
Redirecting stderr to /opt/aem/crx-quickstart/logs/stderr.log
Press CTRL-C to shutdown the Quickstart server...
2020-03-18 15:12:21: AEM started; file: AEM_6.x_Quickstart.jar, port: 4503, runmode: publish,nosamplecontent,local
2020-03-18 15:12:21: Disabling asset workflow
2020-03-18 15:12:21: Asset workflow disabled
2020-03-18 15:12:21: File ".gitkeep" is no zip-file
2020-03-18 15:12:21: Finished installing packages.
2020-03-18 15:12:21: Start system clean-up...
2020-03-18 15:12:21: Enabling asset workflow
2020-03-18 15:12:21: Asset workflow enabled
2020-03-18 15:12:21: Stopping AEM...
Traceback (most recent call last):
  File "aem_installer.py", line 21, in <module>
    helpers.import_packages(file_name, port, runmode)
  File "/opt/aem/helpers.py", line 179, in import_packages
    stop_aem_server(server_process_id)
  File "/opt/aem/helpers.py", line 251, in stop_aem_server
    for childProcess in parent_aem_process.get_children():
AttributeError: 'Process' object has no attribute 'get_children'
ERROR: Service 'publisher' failed to build: The command '/bin/sh -c python aem_installer.py -i AEM_6.x_Quickstart.jar -r publish,nosamplecontent,local -p 4503' returned a non-zero code: 1
```

Since my repo wasn't changed and it worked fine before (I just rebuilded it from the scratch) I guess a dependency got updated and now fails.

Did somebody experienced the same issue or know whats going on?

**Comment by ssachtleben** [comment]
@remcorakers any idea? does it happen for you too?

**Comment by remcorakers** [comment]
Hi @ssachtleben , thanks for the issue report and sorry fo the late reply; this issue slipped my attention. I was able to reproduce the error. It had to do with an update of the Python `psutil.get_children()` method, that should now be `psutil.children()`. I've updated the code with a fix.
